import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrap from "../../common/provider/SessionWrap";
import { ThemeProvder } from "../../common/provider/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrap>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvder
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvder>
        </body>
      </html>
    </SessionWrap>
  );
}
